//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSampleApplication.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Address")]
    public class Address
    {
        
        private string _addressStreet;
        
        private int _addressCityID;
        
        private int _addressStateID;
        
        private int _addressCountryID;
        
        private int _addressID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Address()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AddressStreet")]
        public virtual string AddressStreet
        {
            get
            {
                return this._addressStreet;
            }
            set
            {
                this._addressStreet = value;
                this.SetIsModified("AddressStreet");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AddressCityID")]
        public virtual int AddressCityID
        {
            get
            {
                return this._addressCityID;
            }
            set
            {
                this._addressCityID = value;
                this.SetIsModified("AddressCityID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AddressStateID")]
        public virtual int AddressStateID
        {
            get
            {
                return this._addressStateID;
            }
            set
            {
                this._addressStateID = value;
                this.SetIsModified("AddressStateID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AddressCountryID")]
        public virtual int AddressCountryID
        {
            get
            {
                return this._addressCountryID;
            }
            set
            {
                this._addressCountryID = value;
                this.SetIsModified("AddressCountryID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AddressID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual int AddressID
        {
            get
            {
                return this._addressID;
            }
            set
            {
                this._addressID = value;
                this.SetIsModified("AddressID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("AddressStreet", false);
            this.IsModifiedDictionary.Add("AddressCityID", false);
            this.IsModifiedDictionary.Add("AddressStateID", false);
            this.IsModifiedDictionary.Add("AddressCountryID", false);
            this.IsModifiedDictionary.Add("AddressID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
