//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSampleApplication.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Contact")]
    public class Contact
    {
        
        private string _contactHomePhone;
        
        private string _contactCellPhone;
        
        private string _contactFax;
        
        private string _contactEmail;
        
        private int _contactID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Contact()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ContactHomePhone")]
        public virtual string ContactHomePhone
        {
            get
            {
                return this._contactHomePhone;
            }
            set
            {
                this._contactHomePhone = value;
                this.SetIsModified("ContactHomePhone");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ContactCellPhone")]
        public virtual string ContactCellPhone
        {
            get
            {
                return this._contactCellPhone;
            }
            set
            {
                this._contactCellPhone = value;
                this.SetIsModified("ContactCellPhone");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ContactFax")]
        public virtual string ContactFax
        {
            get
            {
                return this._contactFax;
            }
            set
            {
                this._contactFax = value;
                this.SetIsModified("ContactFax");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ContactEmail")]
        public virtual string ContactEmail
        {
            get
            {
                return this._contactEmail;
            }
            set
            {
                this._contactEmail = value;
                this.SetIsModified("ContactEmail");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ContactID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual int ContactID
        {
            get
            {
                return this._contactID;
            }
            set
            {
                this._contactID = value;
                this.SetIsModified("ContactID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("ContactHomePhone", false);
            this.IsModifiedDictionary.Add("ContactCellPhone", false);
            this.IsModifiedDictionary.Add("ContactFax", false);
            this.IsModifiedDictionary.Add("ContactEmail", false);
            this.IsModifiedDictionary.Add("ContactID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
