//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSampleApplication.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Purpose")]
    public class Purpose
    {
        
        private string _purposeDescription;
        
        private int _purposeID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Purpose()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("PurposeDescription")]
        public virtual string PurposeDescription
        {
            get
            {
                return this._purposeDescription;
            }
            set
            {
                this._purposeDescription = value;
                this.SetIsModified("PurposeDescription");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("PurposeID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual int PurposeID
        {
            get
            {
                return this._purposeID;
            }
            set
            {
                this._purposeID = value;
                this.SetIsModified("PurposeID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("PurposeDescription", false);
            this.IsModifiedDictionary.Add("PurposeID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
