//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSampleApplication.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    using CommonLibrary.Base.Database;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Address")]
    public class Address : List<CodeSampleApplication.Dto.Address>
    {
        
        private CommonLibrary.Base.Database.BaseDatabase _baseDatabase = new CommonLibrary.Base.Database.BaseDatabase();
        
        public Address(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public Address()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {
        
            CodeSampleApplication.Dto.Address dto;
                using(reader)
                {

                while(reader.Read())
                {
            dto = new CodeSampleApplication.Dto.Address();
                    dto.AddressStreet = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("AddressStreet"), reader);
                    dto.AddressCityID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("AddressCityID"), reader);
                    dto.AddressStateID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("AddressStateID"), reader);
                    dto.AddressCountryID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("AddressCountryID"), reader);
                    dto.AddressID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("AddressID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
