//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSampleApplication.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    using CommonLibrary.Base.Database;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Contact")]
    public class Contact : List<CodeSampleApplication.Dto.Contact>
    {
        
        private CommonLibrary.Base.Database.BaseDatabase _baseDatabase = new CommonLibrary.Base.Database.BaseDatabase();
        
        public Contact(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public Contact()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {
        
            CodeSampleApplication.Dto.Contact dto;
                using(reader)
                {

                while(reader.Read())
                {
            dto = new CodeSampleApplication.Dto.Contact();
                    dto.ContactHomePhone = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("ContactHomePhone"), reader);
                    dto.ContactCellPhone = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("ContactCellPhone"), reader);
                    dto.ContactFax = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("ContactFax"), reader);
                    dto.ContactEmail = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("ContactEmail"), reader);
                    dto.ContactID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("ContactID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
