//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSampleApplication.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    using CommonLibrary.Base.Database;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Person_Address")]
    public class Person_Address : List<CodeSampleApplication.Dto.Person_Address>
    {
        
        private CommonLibrary.Base.Database.BaseDatabase _baseDatabase = new CommonLibrary.Base.Database.BaseDatabase();
        
        public Person_Address(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public Person_Address()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {
        
            CodeSampleApplication.Dto.Person_Address dto;
                using(reader)
                {

                while(reader.Read())
                {
            dto = new CodeSampleApplication.Dto.Person_Address();
                    dto.PurposeID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("PurposeID"), reader);
                    dto.PersonID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("PersonID"), reader);
                    dto.AddressID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("AddressID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
