//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSampleApplication.Bo
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    using System.Reflection;
    using CommonLibrary.Enumerations;
    using System.Data.SqlClient;
    using CommonLibrary.Base.Database;
    
    
    public class Person : CodeSampleApplication.Dto.Person
    {

        
        public const string FILL_DB_SETTINGS_EXCEPTION = "Please Fill the DatabaseSmoObjectsAndSettings_Property with a filled DatabaseSmoO" +
            "bjectsAndSettings class and try again";
        
        public const string PRIMARY_KEY_NOT_FOUND_EXCEPTION_VAR_NAME = "PRIMARY_KEY_NOT_FOUND_EXCEPTION_VAR_NAME";
        
        private CommonLibrary.DatabaseSmoObjectsAndSettings _databaseSmoObjectsAndSettings;
        
        private CommonLibrary.Base.Business.BaseBusiness<CodeSampleApplication.Bo.Person, CodeSampleApplication.Dto.Person> _baseBusiness;
        
        private CommonLibrary.Base.Database.BaseDataAccess<CodeSampleApplication.Dto.Person> _baseDataAccess;

        private ModifiedState _modifiedState = ModifiedState.Unchanged;

        public ModifiedState ModifiedState
        {
            get { return _modifiedState; }
            set { _modifiedState = value; }
        }
        
        public Person()
        {
            _baseBusiness =
                new CommonLibrary.Base.Business.BaseBusiness<CodeSampleApplication.Bo.Person, CodeSampleApplication.Dto.Person>();

        }
        
        public Person(CommonLibrary.DatabaseSmoObjectsAndSettings databaseSmoObjectsAndSettings)
        {
            _databaseSmoObjectsAndSettings = databaseSmoObjectsAndSettings;
            _baseDataAccess = 
                new CommonLibrary.Base.Database.BaseDataAccess<CodeSampleApplication.Dto.Person>(_databaseSmoObjectsAndSettings);
            _baseBusiness = 
                new CommonLibrary.Base.Business.BaseBusiness<CodeSampleApplication.Bo.Person, CodeSampleApplication.Dto.Person>();
        }
        
        public Person(CommonLibrary.DatabaseSmoObjectsAndSettings databaseSmoObjectsAndSettings, CodeSampleApplication.Bo.Person filledBo)
        {
            _databaseSmoObjectsAndSettings = databaseSmoObjectsAndSettings;
            _baseDataAccess = 
                new CommonLibrary.Base.Database.BaseDataAccess<CodeSampleApplication.Dto.Person>(_databaseSmoObjectsAndSettings);
            _baseBusiness = 
                new CommonLibrary.Base.Business.BaseBusiness<CodeSampleApplication.Bo.Person, CodeSampleApplication.Dto.Person>();
            this.FillPropertiesFromBo(filledBo);
        }
        
        public virtual CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettings
        {
            get
            {
                return this._databaseSmoObjectsAndSettings;
            }
            set
            {
                this._databaseSmoObjectsAndSettings = value;
            }
        }
        
        private void FillPropertiesFromBo(CodeSampleApplication.Bo.Person filledBo)
        {
            _baseBusiness.FillPropertiesFromBo(filledBo, this);
        }
        
        private void FillThisWithDto(CodeSampleApplication.Dto.Person filledDto)
        {
            _baseBusiness.FillThisWithDto(filledDto, this);
        }
        
        private void FillDtoWithThis()
        {
            _baseBusiness.FillDtoWithThis(this);
        }
        
        private bool BaseDataAccessAvailable()
        {
            bool baseDataAccessAvailable = false;
            if ((_baseDataAccess == null))
            {
                if ((_databaseSmoObjectsAndSettings != null))
                {
                    _baseDataAccess = 
                new CommonLibrary.Base.Database.BaseDataAccess<CodeSampleApplication.Dto.Person>(_databaseSmoObjectsAndSettings);
                }
                baseDataAccessAvailable = true;
            }
            else
            {
                baseDataAccessAvailable = true;
            }
            return baseDataAccessAvailable;
        }
        
        public virtual void Insert()
        {
            if (this.BaseDataAccessAvailable())
            {
                CodeSampleApplication.Dto.Person dto = _baseBusiness.FillDtoWithThis(this);
                CodeSampleApplication.Dto.Person returnDto = _baseDataAccess.Insert(dto);
                this.FillThisWithDto(returnDto);
            }
            else
            {
                throw new System.ApplicationException(FILL_DB_SETTINGS_EXCEPTION);
            }
        }
        
        public virtual void Update()
        {
            if (this.BaseDataAccessAvailable())
            {
                CodeSampleApplication.Dto.Person dto = _baseBusiness.FillDtoWithThis(this);
                CodeSampleApplication.Dto.Person returnDto = _baseDataAccess.Update(dto);
                this.FillThisWithDto(returnDto);
            }
            else
            {
                throw new System.ApplicationException(FILL_DB_SETTINGS_EXCEPTION);
            }
        }
        
        public virtual void Delete()
        {
            if (this.BaseDataAccessAvailable())
            {
                CodeSampleApplication.Dto.Person dto = _baseBusiness.FillDtoWithThis(this);
                CodeSampleApplication.Dto.Person returnDto = _baseDataAccess.Delete(dto);
                this.FillThisWithDto(returnDto);
            }
            else
            {
                throw new System.ApplicationException(FILL_DB_SETTINGS_EXCEPTION);
            }
        }

        public virtual void Insert(SqlConnection connection,
            ref SqlTransaction transaction,
            BaseDatabase.TransactionBehavior transactionBehavior,
            ref object returnValueFromExecution)
        {
            if (this.BaseDataAccessAvailable())
            {
                CodeSampleApplication.Dto.Person dto = _baseBusiness.FillDtoWithThis(this);
                CodeSampleApplication.Dto.Person returnDto = _baseDataAccess.Insert(dto,
                    connection,
                    ref transaction,
                    transactionBehavior,
                    out returnValueFromExecution);
                this.FillThisWithDto(returnDto);
            }
            else
            {
                throw new System.ApplicationException(FILL_DB_SETTINGS_EXCEPTION);
            }
        }

        public virtual void Update(SqlConnection connection,
            ref SqlTransaction transaction,
            BaseDatabase.TransactionBehavior transactionBehavior,
            ref object returnValueFromExecution)
        {
            if (this.BaseDataAccessAvailable())
            {
                CodeSampleApplication.Dto.Person dto = _baseBusiness.FillDtoWithThis(this);
                CodeSampleApplication.Dto.Person returnDto = _baseDataAccess.Update(dto,
                    connection,
                    ref transaction,
                    transactionBehavior,
                    out returnValueFromExecution);
                this.FillThisWithDto(returnDto);
            }
            else
            {
                throw new System.ApplicationException(FILL_DB_SETTINGS_EXCEPTION);
            }
        }

        public virtual void Delete(SqlConnection connection,
            ref SqlTransaction transaction,
            BaseDatabase.TransactionBehavior transactionBehavior,
            ref object returnValueFromExecution)
        {
            if (this.BaseDataAccessAvailable())
            {
                CodeSampleApplication.Dto.Person dto = _baseBusiness.FillDtoWithThis(this);
                CodeSampleApplication.Dto.Person returnDto = _baseDataAccess.Delete(dto,
                    connection,
                    ref transaction,
                    transactionBehavior,
                    out returnValueFromExecution);
                this.FillThisWithDto(returnDto);
            }
            else
            {
                throw new System.ApplicationException(FILL_DB_SETTINGS_EXCEPTION);
            }
        }

        
        public virtual void GetByPrimaryKey()
        {
            if (this.BaseDataAccessAvailable())
            {
                CodeSampleApplication.Dto.Person dto = this;
                List<CodeSampleApplication.Dto.Person> returnDto = _baseDataAccess.Get(dto, CommonLibrary.Enumerations.GetPermutations.ByPrimaryKey);
                if ((returnDto.Count > 0))
                {
                    this.FillThisWithDto(returnDto[0]);
                }
                else
                {
                    throw new System.ApplicationException(PRIMARY_KEY_NOT_FOUND_EXCEPTION_VAR_NAME);
                }
            }
            else
            {
                throw new System.ApplicationException(FILL_DB_SETTINGS_EXCEPTION);
            }
        }
    }
}
